//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int uid { get; set; }
        public string uname { get; set; }
        public string pwd { get; set; }
        public Nullable<int> roleid { get; set; }
    
        public virtual tblRole tblRole { get; set; }
    }
}
